#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

eval $(dircolors -p | sed -e 's/DIR 01;34/DIR 0;34;42/' | dircolors /dev/stdin)

# Customize to your needs...
alias python=python3
alias gi='git init'
alias ga='git add'
alias gc='git commit'
alias gd='git diff'
alias gg='git graph'
alias gs='git status'
alias gb='git branch'
alias gco='git checkout'

plugin=(git ssh-agent)



alias dotfiles='/usr/bin/git --git-dir=/home/jamesedchristie/.dotfiles/ --work-tree=/home/jamesedchristie'
